<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive risk</name>
  <uuid>cc066bae-7efa-4cda-8167-a349f36caa71</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the machine learning scoreboard computed from
 Client Information being Client ,
 Industry being Industry ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
